#!/bin/bash
#Create a symlink to allow TCL loader to find our library in an npm distribution

libdir=$(pwd)
if [ ! -z "$1" ]; then
  libdir="$(realpath $1)"
fi

if [ -z "$TCLLIBPATH" ]; then			#TCL isn't installed anyway
  exit 0
fi

for dir in $TCLLIBPATH; do			#Find first absolute directory in path
  char1=$(echo $dir | cut -b 1)
#  echo "dir:$dir"
  if [ "$char1" = '/' ]; then break; fi
done
dir='/usr/lib'

echo "dir:$dir"
link="$dir/wylib"
if [ -h link ]; then
  rm $link
elif [ ! -d link ]; then
  echo ln -s $libdir $link
else
  echo "Unable to find a place to link wylib TCL"
  exit 1
fi
