#This file is automatically generated by wmmkpkg.

package ifneeded wylib 0.35 [list set wylib_library $dir]\n[list source [file join $dir init.tcl]]\n[list tclPkgSetup $dir wylib 0.35 {
    {libwylib.so load {checkline checkpwd crypwd getpwinfo money rpn rpx }}
    {args.tcl	source {argproc prargs argform unabbrev argnorm xswitch xswitchs swores swexp }}
    {calc.tcl	source {::calc::calc ::calc::dia }}
    {cal.tcl	source {::cal::cal ::cal::dia ::cal::months }}
    {cdew.tcl	source {::cdew::cdew }}
    {color.tcl	source {::color::edit ::color::bright }}
    {date.tcl	source {::date::seconds ::date::date ::date::date_tim ::date::tim ::date::norm ::date::dia ::date::diamd ::date::range ::date::compare }}
    {datim.tcl	source {::datim::datim ::datim::dia }}
    {dbe.tcl	source {::dbe::dbe }}
    {dbp.tcl	source {::dbp::dbp ::dbp::table }}
    {dbs.tcl	source {::dbs::dbs ::dbs::saved_queries }}
    {ddis.tcl	source {::ddis::do_dist ::ddis::dprompt }}
    {debug.tcl	source {::debug::interpret ::debug::command }}
    {dew.tcl	source {::dew::dew ::dew::align ::dew::scm ::dew::edarr }}
    {dia.tcl	source {::dia::ask ::dia::err ::dia::warn ::dia::brief ::dia::query ::dia::pquery ::dia::dia ::dia::unget }}
    {docedit.tcl	source {::docedit::fext ::docedit::view ::docedit::edit ::docedit::build_ps ::docedit::ffmt ::docedit::scale }}
    {edwin.tcl	source {::edwin::edwin }}
    {etext.tcl	source {::etext::etext ::etext::filename }}
    {etwadd.tcl	source {::etwadd::create ::etwadd::lout ::etwadd::get ::etwadd::dprompt ::etwadd::cfig }}
    {etwatt.tcl	source {::etwatt::create ::etwatt::lout ::etwatt::get ::etwatt::flist }}
    {etwbom.tcl	source {::etwbom::create ::etwbom::lout }}
    {etwcmt.tcl	source {::etwcmt::create ::etwcmt::lout ::etwcmt::get }}
    {etwfig.tcl	source {::etwfig::create ::etwfig::lout }}
    {etwfmt.tcl	source {::etwfmt::create ::etwfmt::lout }}
    {etwinc.tcl	source {::etwinc::create ::etwinc::lout }}
    {etwpar.tcl	source {::etwpar::create ::etwpar::lout ::etwpar::get }}
    {etwpsm.tcl	source {::etwpsm::create ::etwpsm::lout }}
    {etwqcc.tcl	source {::etwqcc::create ::etwqcc::lout }}
    {etwref.tcl	source {::etwref::create ::etwref::lout ::etwref::get }}
    {etwsec.tcl	source {::etwsec::create ::etwsec::lout }}
    {etwsig.tcl	source {::etwsig::create ::etwsig::enable ::etwsig::save ::etwsig::lout ::etwsig::get ::etwsig::default }}
    {etwtab.tcl	source {::etwtab::create ::etwtab::lout ::etwtab::get ::etwtab::margin }}
    {etw.tcl	source {::etw::create ::etw::splist ::etw::title ::etw::widgcmd }}
    {exedit.tcl	source {::exedit::exedit }}
    {form.tcl	source {::form::form }}
    {help.tcl	source {::help::help }}
    {ksock.tcl	source {::ksock::init ::ksock::message }}
    {lbsel.tcl	source {::lbsel::lbsel }}
    {lib.tcl	source {::lib::cwatch ::lib::cnorm ::lib::cfig ::lib::cwait }}
    {loglst.tcl	source {::loglst::loglst ::loglst::dia }}
    {logtime.tcl	source {::logtime::logtime ::logtime::dia }}
    {lout.tcl	source {::lout::quote ::lout::preview ::lout::parse ::lout::cleanup ::lout::addincl }}
    {macro.tcl	source {::macro::macro }}
    {mbar.tcl	source {::mbar::mbar }}
    {mdew.tcl	source {::mdew::mdew }}
    {misc.tcl	source {nop cap_first uwin round_dollar norm_dollar comma_dollar labtpt margins wrap uproc dowhile lremove widgclose widginit shq debug mytop mypar plural def }}
    {mlb.tcl	source {::mlb::mlb }}
    {osdep.tcl	source {::osdep::cmd_esc ::osdep::filetypes ::osdep::smash_file ::osdep::unsmash_data ::osdep::print }}
    {passwd.tcl	source {::passwd::init ::passwd::ok }}
    {photo.tcl	source {::photo::photo ::photo::edit ::photo::readfile }}
    {pref.tcl	source {::pref::init ::pref::auto ::pref::restore ::pref::clean ::pref::external }}
    {print.tcl	source {::print::print ::print::grab }}
    {report.tcl	source {::report::report ::report::padlines ::report::linkbind }}
    {scanvas.tcl	source {::scanvas::scanvas ::scanvas::drag }}
    {scm.tcl	source {::scm::scm ::scm::dia }}
    {search.tcl	source {::search::search }}
    {sfile.tcl	source {::sfile::sfile ::sfile::top ::sfile::get ::sfile::dia ::sfile::pref }}
    {sizer.tcl	source {::sizer::sizer ::sizer::create }}
    {spell.tcl	source {::spell::spell }}
    {spin.tcl	source {::spin::spin }}
    {sql.tcl	source {::sql::configure ::sql::init ::sql::cget ::sql::listen ::sql::disconnect ::sql::connect ::sql::exe ::sql::x ::sql::one ::sql::value ::sql::qlist ::sql::quote ::sql::esc ::sql::escape ::sql::bton ::sql::quote_list ::sql::lo_import }}
    {stext.tcl	source {::stext::stext }}
    {tabs.tcl	source {::tabs::tabs }}
    {tim.tcl	source {::tim::tim ::tim::dia }}
    {top.tcl	source {::top::top ::top::dbep ::top::dbp ::top::closewin ::top::closeall ::top::menu }}
    {tsearch.tcl	source {::tsearch::tsearch }}
    {wboard.tcl	source {::wboard::wboard }}
    {wbutton.tcl	source {::wbutton::button }}
    {wcanvas.tcl	source {::ww::canvas }}
    {wcheckbutton.tcl	source {::wcheckbutton::checkbutton }}
    {web.tcl	source {::web::web ::web::zip ::web::fetch ::web::view ::web::zip_lookup }}
    {wentry.tcl	source {::wentry::entry }}
    {wframe.tcl	source {::wframe::frame }}
    {wkeys.tcl	source {::wkeys::movers ::wkeys::wtext ::wkeys::wentry }}
    {wlabel.tcl	source {::ww::label }}
    {wlistbox.tcl	source {::wlistbox::listbox }}
    {wmenubutton.tcl	source {::wmenubutton::menubutton }}
    {wmenu.tcl	source {::wmenu::menu }}
    {wmessage.tcl	source {::ww::message }}
    {wradiobutton.tcl	source {::ww::radiobutton }}
    {wscale.tcl	source {::ww::scale }}
    {wtext.tcl	source {::wtext::text ::wtext::movers }}
    {ww.tcl	source {::ww::hook ::ww::modgen ::ww::modblock }}
    {zip.tcl	source {::zip::gzip ::zip::gunzip }}
}]
